apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: homebase
  name: kanban-deployment
  labels:
    app: kanban
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kanban
  template:
    metadata:
      labels:
        app: kanban
    spec:
      containers:
      - name: kanban
        # image: si3mshady/dnd-kanban-practice
        image: si3mshady/kanban3
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: kanban-service
spec:
  type: NodePort

  selector:
    app: kanban
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 3000
      targetPort: 3000
      protocol: TCP
      nodePort: 31000
 
