apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: kanban
  name: kanban
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kanban
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.27.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: kanban
    spec:
      containers:
        - image: si3mshady/dnd-kanban-practice
          name: kanban
          ports:
            - containerPort: 5173
          resources: {}
      restartPolicy: Always
status: {}
